### ISSUE TITLE
Collab ox-serve not using GPU

### ISSUE THREAD

**Issue by siegmundbio** [zoombya/ox-serve#4]
Howdy,
Both an issue and a solution i found.
I was trying to use the collab notebook you linked for oxdna sims, however the cuda version utilised in current collab notebooks was incompatible with oxDNA, so the GPU wasn't being used.
So I had to add this code to the first cell to downgrade CUDA and now GPU ox-serve relaxations work fine :)
 
!nvidia-smi
!nvcc --version
%cd /usr/local/
!rm -rf cuda
!ln -s /usr/local/cuda-10.1 /usr/local/cuda
!stat cuda

**Comment by m-matthies** [comment]
Hi, I just checked the code in the colab [link ](https://colab.research.google.com/drive/1nFC9zy-wEwwl8vlJZAbQZZofavP4PXvL#scrollTo=C_8TB2t5gxDg) we provide. 
It's running fine without your modifications. If you are able to start an MD simulation using ox-serve 
you are using the GPU. As it has **no** fallback option to use CPU instead.
One problem might be that you got assigned to a strange node, but otherwise the code should run fine.
As an alternative option you can also use the public server from **Nanobase.org**. 
Which should offer similar performance as  K80 available from Colab.

**Comment by siegmundbio** [comment]
I was slightly wrong in my remembering, i couldn't get ox-serve to use the GPU so was using the CPU until I learnt to downgraded CUDA. 
I just tried running your notebook again from a free collab account (K80) and got the same errors as before. Interestingly, i've recently got a collab pro account for ox-serve and when I ran your code with a P100 there was no problem. During your test of the code were you allocated a K80? I've copied both the outputs for the free K80 and pro P100 into the attached word doc for reference
[oxserve_errors.docx](https://github.com/sulcgroup/ox-serve/files/7329263/oxserve_errors.docx)

**Comment by m-matthies** [comment]
Interesting, I did try this on K80's as well. Possibly google has different nodes operating slightly different.
At least in the US they all seem to behave. It is cool that you have found a solution with the downgrade of the version. 
Also your case has made me curious to try out another thing. 
You can compile oxDNA on a GPU node and save the result in your google drive.
This allows you to skip the compilation step while running that ox-serve colab and if you store 
all other files like ox-serve source codes on your google drive you can skip the configuration steps as well. 
So your workflow could be: 
- open colab (GPU)
- mount google drive with ox-serve
- start up the server and ngrok 
- use it ;)
